[LAB-14] Retrieve attached content for Assignment/Submission
PNU-SE-3-team-7/LabControl pull request #15
Opened 2024-06-18 15:23 UTC by Marko-Shevchuk

2024-06-18 15:24 UTC, ArsenOOO7 commented on src/main/java/com/pnu/lab/control/labcontrol/api/AssignmentAttachedContentController.java
> +    public AssignmentAttachedContent update(@Valid @RequestBody AssignmentAttachedContent assignmentAttachedContent) {
U cannot update attached content, only create/delete

2024-06-18 15:24 UTC, ArsenOOO7 commented on src/main/java/com/pnu/lab/control/labcontrol/api/SubmissionAttachedContentController.java
> +    @PutMapping
+1

2024-06-18 15:28 UTC, ArsenOOO7 approved these changes

2024-06-18 15:29 UTC, JJerome-NM requested changes
+1

2024-06-18 15:33 UTC, ArsenOOO7 requested changes
When u remove either Assignment or Submission, u should also delete attached content and comments

2024-06-19 07:01 UTC, ArsenOOO7 approved these changes

2024-06-19 16:22 UTC, JJerome-NM approved these changes
**_Request changes_**

2024-06-19 16:28 UTC, merged